USE master
GO
CREATE DATABASE school
GO
USE school
GO
CREATE TABLE TEACHER (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  SALARY INT,
  EMPLOYMENT_START DATE NOT NULL
);

CREATE TABLE DEPARTMENT_STAFF (
  DEPARTMENT_NAME VARCHAR(20) NOT NULL,
  ID INT NOT NULL FOREIGN KEY REFERENCES TEACHER(ID),
  CONSTRAINT PK_DEPT_STAFF PRIMARY KEY(DEPARTMENT_NAME,ID)
);

CREATE TABLE LOCKER (
  LOCKER_NUMBER INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  COMBINATION_1 INT NOT NULL,
  COMBINATION_2 INT NOT NULL,
  COMBINATION_3 INT NOT NULL,
);

CREATE TABLE STUDENT (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  LOCKER_NUMBER INT FOREIGN KEY REFERENCES LOCKER(LOCKER_NUMBER)
);

CREATE TABLE StAFF_PURCHASE (
  ORDER_REFERENCE INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  ID INT FOREIGN KEY REFERENCES TEACHER(ID),
  ITEM VARCHAR(50),
  PRICE FLOAT(2) NOT NULL,
  AMOUNT INT NOT NULL
);